### ISSUE TITLE
Octal literals are not allowed in strict mode

### ISSUE THREAD

**Issue by jsonmaur** [tj/nib#316]
Running with Node v4.1.1 with --use-strict flag. When requiring package with ```var nib = require('nib');```, I get the following error:

```
/Users/.../node_modules/nib/node_modules/stylus/lib/visitor/evaluator.js:1527
  console.warn('\033[33mWarning:\033[0m ' + msg);
                                 ^^

SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jdmaurer/Projects/zab/zab-cli/node_modules/nib/node_modules/stylus/lib/nodes/node.js:12:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

**Comment by jdmaurer** [comment]
Looks like this may be a problem coming from Stylus itself... not sure if it's because of an outdated version or what. Let me know if I need to post this issue in the Stylus repo instead.

**Comment by alewisohn** [comment]
This is because the stylus dependency is out of date. If you update to the latest version of Stylus, the octal literals have been removed.

**Comment by jsonmaur** [comment]
Actually forgot about this issue, I got it solved awhile back. Thanks for the response though :)

**Comment by alewisohn** [comment]
This is not solved. Latest version of nib on npm still requires a version of stylus that uses octal literals.
